version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "weekly"
    day: "friday"
    time: "12:00"
    timezone: "Europe/Zurich"
- package-ecosystem: pip
  directory: "/api"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  commit-message:
    prefix: chore
    include: scope
- package-ecosystem: npm
  directory: "/ember"
  schedule:
    interval: weekly
    day: friday
    time: "12:00"
    timezone: "Europe/Zurich"
  versioning-strategy: increase
  commit-message:
    prefix: chore
    include: scope
