version: "3.9"
services:
  db:
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - psqldata:/var/lib/postgresql/data
volumes:
  psqldata:
